"""keep results/vit_runs.json and RESULTS_VIT.md in step with the ViT runs

    python scripts/collect_vit.py ingest notebook-85.log
    python scripts/collect_vit.py label <run> <letter> <what...>
    python scripts/collect_vit.py render

The ViT table is read on the common grid k/8 (0.25, 0.375, ..., 1.0), the
only widths every method in it trains or reads, so it does not fit
results/runs.json and its sixteen widths. Same log format and the same
post-calibration lines as scripts/collect_results.py.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from collect_results import CAL_LINE, text_of, config_seed  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STORE = os.path.join(ROOT, 'results', 'vit_runs.json')
PAGE = os.path.join(ROOT, 'RESULTS_VIT.md')
GRID = [0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1.0]


def load():
    if not os.path.exists(STORE):
        return {'widths': GRID, 'runs': []}
    with open(STORE, encoding='utf-8') as handle:
        return json.load(handle)


def save(store):
    with open(STORE, 'w', encoding='utf-8') as handle:
        json.dump(store, handle, indent=2, ensure_ascii=False)
        handle.write('\n')


def ingest(path):
    store = load()
    found = {}
    for match in CAL_LINE.finditer(text_of(path)):
        found.setdefault(match.group('run'), {})[
            float(match.group('width'))] = (
                100.0 * (1.0 - float(match.group('top1'))),
                float(match.group('loss')))
    if not found:
        raise SystemExit('no post-calibration validation lines in ' + path)
    for run, table in sorted(found.items()):
        # MatFormer cannot reach the narrow grid points: keep what it
        # reads and leave the rest empty rather than skipping the run.
        missing = [w for w in GRID if w not in table]
        if len(missing) == len(GRID):
            print('skipped {}: no value on the grid'.format(run))
            continue
        if missing:
            print('{}: no value at {}'.format(run, missing))
        entry = {'name': run, 'letter': '?',
                 'what': 'ingested from ' + os.path.basename(path),
                 'top1': [round(table[w][0], 2) if w in table else None
                          for w in GRID],
                 'nll': [table[w][1] if w in table else None
                         for w in GRID]}
        seed = config_seed(run)
        if seed is not None:
            entry['seed'] = seed
        existing = [r for r in store['runs'] if r['name'] == run]
        if existing:
            existing[0].update({k: v for k, v in entry.items()
                                if k not in ('letter', 'what')})
            print('updated', run)
        else:
            store['runs'].append(entry)
            print('added  ', run, '(set its letter and description)')
    save(store)
    render()


def label(run, letter, what):
    store = load()
    hits = [r for r in store['runs'] if r['name'] == run]
    if not hits:
        raise SystemExit('no run ' + run)
    hits[0].update(letter=letter, what=what)
    save(store)
    render()


def render():
    store = load()
    lines = ['# ViT results', '',
             'CIFAR-100, a ViT with patch 4, dim 384, 8 heads of 48, depth 7, '
             'MLP ratio 2, trained 100 epochs with the shared ViT recipe '
             '(notebook 84). Top-1 after calibration on the common grid k/8, '
             'the only widths every method reads; the mean is over those '
             'seven widths, or over the ones a run reaches, marked with '
             'their count. Generated by `scripts/collect_vit.py`.', '',
             '| Run | Seed | ' + ' | '.join('%g' % w for w in GRID)
             + ' | Mean | What |',
             '|---|---|' + '---|' * len(GRID) + '---|---|']
    def mean(r):
        present = [v for v in r['top1'] if v is not None]
        return sum(present) / len(present), len(present)

    for r in sorted(store['runs'], key=lambda r: -mean(r)[0]):
        value, count = mean(r)
        shown = '**{:.2f}**'.format(value)
        if count < len(GRID):
            shown += ' ({} of {})'.format(count, len(GRID))
        lines.append('| **{}** | {} | {} | {} | {} |'.format(
            r['letter'], r.get('seed', ''),
            ' | '.join('-' if v is None else '%.2f' % v for v in r['top1']),
            shown, r['what']))
    with open(PAGE, 'w', encoding='utf-8') as handle:
        handle.write('\n'.join(lines) + '\n')
    print('wrote RESULTS_VIT.md ({} runs)'.format(len(store['runs'])))


if __name__ == '__main__':
    if len(sys.argv) >= 3 and sys.argv[1] == 'ingest':
        ingest(sys.argv[2])
    elif len(sys.argv) >= 5 and sys.argv[1] == 'label':
        label(sys.argv[2], sys.argv[3], ' '.join(sys.argv[4:]))
    elif len(sys.argv) == 2 and sys.argv[1] == 'render':
        render()
    else:
        raise SystemExit(__doc__)
